### ISSUE TITLE
What am I doing wrong? 

### ISSUE THREAD

**Issue by matthewsinclair** [clearsightstudio/ProMotion#699]
I have just updated to RM 3.11 and ProMotion 2.4.2 and without changing any code, I've rebuilt everything from scratch. Now, code that was working before, is failing with the following error:

```
...
  Simulate ./build/iPhoneSimulator-8.1-Development/T-UIKit.app
(main)> 2015-05-23 11:23:52.279 T-UIKit[92150:9900632] table.rb:207:in `tableView:heightForRowAtIndexPath:': wrong number of arguments (1 for 2) (ArgumentError)
	from searchable.rb:19:in `make_searchable:'
	from table.rb:49:in `set_up_searchable'
	from table.rb:20:in `screen_setup'
	from support.rb:17:in `try:'
	from screen_module.rb:20:in `screen_init:'
	from table_view_controller.rb:5:in `new:'
	from shopper_featured_screen.rb:11:in `new:'
	from shopper_home_screen.rb:10:in `on_init'
	from support.rb:17:in `try:'
	from screen_module.rb:19:in `screen_init:'
	from view_controller.rb:5:in `new:'
	from delegate_module.rb:51:in `open:'
	from app_delegate.rb:8:in `on_load:'
	from delegate_module.rb:16:in `application:didFinishLaunchingWithOptions:'
2015-05-23 11:23:52.284 T-UIKit[92150:9900632] table.rb:207:in `tableView:heightForRowAtIndexPath:': wrong number of arguments (1 for 2) (ArgumentError)
	from searchable.rb:19:in `make_searchable:'
	from table.rb:49:in `set_up_searchable'
	from table.rb:20:in `screen_setup'
	from support.rb:17:in `try:'
	from screen_module.rb:20:in `screen_init:'
	from table_view_controller.rb:5:in `new:'
	from shopper_featured_screen.rb:11:in `new:'
	from shopper_home_screen.rb:10:in `on_init'
	from support.rb:17:in `try:'
	from screen_module.rb:19:in `screen_init:'
	from view_controller.rb:5:in `new:'
	from delegate_module.rb:51:in `open:'
	from app_delegate.rb:8:in `on_load:'
	from delegate_module.rb:16:in `application:didFinishLaunchingWithOptions:'
2015-05-23 11:23:52.328 T-UIKit[92150:9900632] *** Terminating app due to uncaught exception 'ArgumentError', reason: 'table.rb:207:in `tableView:heightForRowAtIndexPath:': wrong number of arguments (1 for 2) (ArgumentError)
	from searchable.rb:19:in `make_searchable:'
	from table.rb:49:in `set_up_searchable'
	from table.rb:20:in `screen_setup'
	from support.rb:17:in `try:'
	from screen_module.rb:20:in `screen_init:'
	from table_view_controller.rb:5:in `new:'
	from shopper_featured_screen.rb:11:in `new:'
	from shopper_home_screen.rb:10:in `on_init'
	from support.rb:17:in `try:'
	from screen_module.rb:19:in `screen_init:'
	from view_controller.rb:5:in `new:'
	from delegate_module.rb:51:in `open:'
	from app_delegate.rb:8:in `on_load:'
	from delegate_module.rb:16:in `application:didFinishLaunchingWithOptions:'
'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001056aac65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000101261bb7 objc_exception_throw + 45
	2   T-UIKit                             0x00000001007946cf _ZL10__vm_raisev + 399
	3   T-UIKit                             0x00000001007947fd rb_vm_raise + 205
	4   T-UIKit                             0x00000001006916f9 rb_exc_raise + 9
	5   T-UIKit                             0x000000010068b5c5 rb_raise + 245
	6   T-UIKit                             0x0000000100765ca6 rb_vm_dispatch + 6662
	7   T-UIKit                             0x00000001000b54fc vm_dispatch + 1436
	8   T-UIKit                             0x00000001003d407f rb_scope__tableView:heightForRowAtIndexPath:__ + 159
	9   T-UIKit                             0x00000001003d42fd __unnamed_155 + 61
	10  UIKit                               0x000000010452d2eb __66-[UISectionRowData refreshWithSection:tableView:tableViewRowData:]_block_invoke + 302
	11  UIKit                               0x000000010452c97e -[UISectionRowData refreshWithSection:tableView:tableViewRowData:] + 4125
	12  UIKit                               0x0000000104531f1c -[UITableViewRowData rectForFooterInSection:heightCanBeGuessed:] + 324
	13  UIKit                               0x0000000104532060 -[UITableViewRowData heightForTable] + 56
	14  UIKit                               0x000000010437b760 -[UITableView _updateContentSize] + 381
	15  UIKit                               0x0000000104395bab -[UITableView setTableHeaderView:] + 571
	16  T-UIKit                             0x00000001000c833a __unnamed_81 + 90
	17  T-UIKit                             0x0000000100765b1e rb_vm_dispatch + 6270
	18  T-UIKit                             0x00000001000b54fc vm_dispatch + 1436
	19  T-UIKit                             0x00000001003bdf0b rb_scope__make_searchable:__ + 1387
	20  T-UIKit                             0x0000000100765f89 rb_vm_dispatch + 7401
	21  T-UIKit                             0x00000001000b54fc vm_dispatch + 1436
	22  T-UIKit                             0x00000001003cf52a rb_scope__set_up_searchable__ + 666
	23  T-UIKit                             0x0000000100765f89 rb_vm_dispatch + 7401
	24  T-UIKit                             0x00000001000b54fc vm_dispatch + 1436
	25  T-UIKit                             0x00000001003ce78e rb_scope__screen_setup__ + 174
	26  T-UIKit                             0x0000000100765f89 rb_vm_dispatch + 7401
	27  T-UIKit                             0x000000010075c92f send_internal + 719
	28  T-UIKit                             0x00000001007659c5 rb_vm_dispatch + 5925
	29  T-UIKit                             0x00000001000b54fc vm_dispatch + 1436
	30  T-UIKit                             0x0000000100364f81 rb_scope__try:__ + 225
	31  T-UIKit                             0x0000000100765f89 rb_vm_dispatch + 7401
	32  T-UIKit                             0x00000001000b54fc vm_dispatch + 1436
	33  T-UIKit                             0x000000010037c777 rb_scope__screen_init:__ + 663
	34  T-UIKit                             0x0000000100765f89 rb_vm_dispatch + 7401
	35  T-UIKit                             0x00000001000b54fc vm_dispatch + 1436
	36  T-UIKit                             0x000000010035f8af rb_scope__new:__ + 431
	37  T-UIKit                             0x0000000100765f89 rb_vm_dispatch + 7401
	38  T-UIKit                             0x00000001000b54fc vm_dispatch + 1436
	39  T-UIKit                             0x00000001005a7345 rb_scope__new:__ + 149
	40  T-UIKit                             0x0000000100765f89 rb_vm_dispatch + 7401
	41  T-UIKit                             0x00000001000b54fc vm_dispatch + 1436
	42  T-UIKit                             0x00000001006436fa rb_scope__on_init__ + 266
	43  T-UIKit                             0x0000000100765f89 rb_vm_dispatch + 7401
	44  T-UIKit                             0x000000010075c92f send_internal + 719
	45  T-UIKit                             0x00000001007659c5 rb_vm_dispatch + 5925
	46  T-UIKit                             0x00000001000b54fc vm_dispatch + 1436
	47  T-UIKit                             0x0000000100364f81 rb_scope__try:__ + 225
	48  T-UIKit                             0x0000000100765f89 rb_vm_dispatch + 7401
	49  T-UIKit                             0x00000001000b54fc vm_dispatch + 1436
	50  T-UIKit                             0x000000010037c711 rb_scope__screen_init:__ + 561
	51  T-UIKit                             0x0000000100765f89 rb_vm_dispatch + 7401
	52  T-UIKit                             0x00000001000b54fc vm_dispatch + 1436
	53  T-UIKit                             0x00000001003626af rb_scope__new:__ + 639
	54  T-UIKit                             0x0000000100765f89 rb_vm_dispatch + 7401
	55  T-UIKit                             0x00000001000b54fc vm_dispatch + 1436
	56  T-UIKit                             0x000000010038b90b rb_scope__open:__ + 203
	57  T-UIKit                             0x0000000100765f89 rb_vm_dispatch + 7401
	58  T-UIKit                             0x00000001000b54fc vm_dispatch + 1436
	59  T-UIKit                             0x0000000100645013 rb_scope__on_load:__ + 515
	60  T-UIKit                             0x0000000100765f89 rb_vm_dispatch + 7401
	61  T-UIKit                             0x00000001000b54fc vm_dispatch + 1436
	62  T-UIKit                             0x000000010038a08a rb_scope__application:didFinishLaunchingWithOptions:__ + 202
	63  T-UIKit                             0x000000010038a28d __unnamed_42 + 61
	64  UIKit                               0x000000010429d788 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 240
	65  UIKit                               0x000000010429e397 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 2540
	66  UIKit                               0x00000001042a11de -[UIApplication _runWithMainScene:transitionContext:completion:] + 1349
	67  UIKit                               0x00000001042a00d5 -[UIApplication workspaceDidEndTransaction:] + 179
	68  FrontBoardServices                  0x000000010ab7e5e5 __31-[FBSSerialQueue performAsync:]_block_invoke_2 + 21
	69  CoreFoundation                      0x00000001055de41c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	70  CoreFoundation                      0x00000001055d4165 __CFRunLoopDoBlocks + 341
	71  CoreFoundation                      0x00000001055d3f25 __CFRunLoopRun + 2389
	72  CoreFoundation                      0x00000001055d3366 CFRunLoopRunSpecific + 470
	73  UIKit                               0x000000010429fb42 -[UIApplication _run] + 413
	74  UIKit                               0x00000001042a2900 UIApplicationMain + 1282
	75  T-UIKit                             0x00000001000be0df main + 111
	76  libdyld.dylib                       0x0000000108146145 start + 1
	77  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type ArgumentError
```

Am I doing something stupendously mad here, or has something quite profound changed with the way `tableView:heightForRowAtIndexPath` works?

Thanks,
M@

**Comment by matthewsinclair** [comment]
Hmm. I just switched over to RedPotion gem `1.2.0` instead of the ProMotion gem `2.4.2` (noticing that RedPotion uses ProMotion `2.3.1` instead of `2.4.2`) and the problem has gone away. I'm happy to close this for now as I don't need to be on the bleeding edge of ProMotion while I port from MotionKit over RedPotion. But I'd still be curious to know what the problem was, if anyone knows and can diagnose it easily enough.

**Comment by jamonholmgren** [comment]
Here's the offending line:

https://github.com/clearsightstudio/ProMotion/blob/master/lib/ProMotion/table/table.rb#L207

**Comment by matthewsinclair** [comment]
This seems to have come back in `redpotion-1.3.0`, which is now using `ProMotion-2.4.2`. Am I the only person experiencing this issue? I'll try to track it down down now ...

**Comment by jamonholmgren** [comment]
I haven't been running into anything, Matt, with my apps. Let me know what you find!

**Comment by matthewsinclair** [comment]
Hmm, I kind of figured it had to be something whacky at my end. But what ...

**Comment by matthewsinclair** [comment]
Aha. I have my own `cell_at` method, a little further up the inheritance hierarchy. D'Oh.

**Comment by jamonholmgren** [comment]
Is that a random name collision or were you trying to override our new method?

**Comment by matthewsinclair** [comment]
I've had a `cell_at` for a while. Your new one was clashing with my old one. :) Don't worry, I've removed mine now.

**Comment by jamonholmgren** [comment]
The downside to using short method names. :) Sorry about that! cc @markrickert

**Comment by matthewsinclair** [comment]
Gosh, don't worry about it. I should have realised. Totally my bad.
