### ISSUE TITLE
uninitialized constant ProMotion::TableViewCellModule::SDWebImageRefreshCached (NameError)

### ISSUE THREAD

**Issue by evansobkowicz** [clearsightstudio/ProMotion#713]
Just switched to use SDWebImage and I'm running into this error. Did I miss a step in the migration? 

My Podfile includes the following:

```
  - SDWebImage (3.7.2):
    - SDWebImage/Core (= 3.7.2)

```

Remote Image Code

```ruby

remote_image: {
                url: url_string,
                placeholder: 'placeholder',
                size: 40,
                radius: (40 / 2),
                content_mode: :scale_aspect_fill,
              },

```

Error description:

```bash
2015-07-03 11:54:09.385 MyApp[11855:7430900] table_view_cell_module.rb:55:in `set_remote_image': uninitialized constant ProMotion::TableViewCellModule::SDWebImageRefreshCached (NameError)
	from table_view_cell_module.rb:16:in `setup:'
	from table_builder.rb:22:in `create_table_cell:'
	from table.rb:196:in `tableView:cellForRowAtIndexPath:'
2015-07-03 11:54:09.401 MyApp[11855:7430900] *** Terminating app due to uncaught exception 'NameError', reason: 'table_view_cell_module.rb:55:in `set_remote_image': uninitialized constant ProMotion::TableViewCellModule::SDWebImageRefreshCached (NameError)
	from table_view_cell_module.rb:16:in `setup:'
	from table_builder.rb:22:in `create_table_cell:'
	from table.rb:196:in `tableView:cellForRowAtIndexPath:'

**Comment by evansobkowicz** [comment]
Never mind, fixed after a `rake clean:all` and reinstalling the pods, as well as resetting the simulator.
