### ISSUE TITLE
undefined method `[]' for nil:NilClass when searching a PM:TableScreen

### ISSUE THREAD

**Issue by markrickert** [clearsightstudio/ProMotion#733]
I've been getting this issue while searching on and off ad I thought it was the way I was creating cells, but i've gotten it on three different applications now. Logging here to see if anyone else has the same issue or has an idea of the cause/solution.

It only happens when typing in a PM::TableScreen's search bar.

```
2015-08-16 09:53:29.979 BJCPStyles[28397:18813275] table_data_builder.rb:4:in `set_data_cell_defaults:': undefined method `[]' for nil:NilClass (NoMethodError)
	from table_data.rb:30:in `cell:'
	from table.rb:171:in `cell_at:'
	from table.rb:221:in `tableView:canEditRowAtIndexPath:'
2015-08-16 09:53:30.011 BJCPStyles[28397:18813275] *** Terminating app due to uncaught exception 'NoMethodError', reason: 'table_data_builder.rb:4:in `set_data_cell_defaults:': undefined method `[]' for nil:NilClass (NoMethodError)
	from table_data.rb:30:in `cell:'
	from table.rb:171:in `cell_at:'
	from table.rb:221:in `tableView:canEditRowAtIndexPath:'
'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001032b9c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000100b82bb7 objc_exception_throw + 45
	2   BJCPStyles                          0x0000000100577b6f _ZL10__vm_raisev + 399
	3   BJCPStyles                          0x0000000100577c9d rb_vm_raise + 205
	4   BJCPStyles                          0x0000000100474b79 rb_exc_raise + 9
	5   BJCPStyles                          0x0000000100575f12 rb_vm_method_missing + 786
	6   BJCPStyles                          0x0000000100548e65 rb_vm_dispatch + 5925
	7   BJCPStyles                          0x00000001005475fd rb_vm_trigger_method_missing + 1053
	8   BJCPStyles                          0x000000010054885f rb_vm_dispatch + 4383
	9   BJCPStyles                          0x0000000100015f0c vm_dispatch + 1436
	10  BJCPStyles                          0x000000010001a1ea vm_fast_aref + 522
	11  BJCPStyles                          0x000000010037fa74 rb_scope__set_data_cell_defaults:__ + 68
	12  BJCPStyles                          0x0000000100549429 rb_vm_dispatch + 7401
	13  BJCPStyles                          0x0000000100015f0c vm_dispatch + 1436
	14  BJCPStyles                          0x00000001003bf172 rb_scope__cell:__ + 706
	15  BJCPStyles                          0x0000000100549429 rb_vm_dispatch + 7401
	16  BJCPStyles                          0x0000000100015f0c vm_dispatch + 1436
	17  BJCPStyles                          0x00000001003aa232 rb_scope__cell_at:__ + 194
	18  BJCPStyles                          0x0000000100549429 rb_vm_dispatch + 7401
	19  BJCPStyles                          0x0000000100015f0c vm_dispatch + 1436
	20  BJCPStyles                          0x00000001003ada32 rb_scope__tableView:canEditRowAtIndexPath:__ + 194
	21  BJCPStyles                          0x00000001003adb1d __unnamed_239 + 61
	22  UIKit                               0x0000000101f97e1f -[UITableView _canEditRowAtIndexPath:] + 63
	23  UIKit                               0x0000000101fb2684 -[UITableView _setupCell:forEditing:atIndexPath:animated:updateSeparators:] + 137
	24  UIKit                               0x0000000101fab4aa __53-[UITableView _configureCellForDisplay:forIndexPath:]_block_invoke + 2464
	25  UIKit                               0x0000000101f2964e +[UIView(Animation) performWithoutAnimation:] + 65
	26  UIKit                               0x0000000101faaafb -[UITableView _configureCellForDisplay:forIndexPath:] + 312
	27  UIKit                               0x0000000101fb2a01 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 533
	28  UIKit                               0x0000000101f91208 -[UITableView _updateVisibleCellsNow:isRecursive:] + 2853
	29  UIKit                               0x0000000101fa0174 -[UITableView _visibleCells] + 27
	30  UIKit                               0x0000000101fa981e -[UITableView _scrollFirstResponderCellToVisible:] + 94
	31  UIKit                               0x0000000101fb5b0c -[UITableView _adjustForAutomaticKeyboardInfo:animated:lastAdjustment:] + 122
	32  UIKit                               0x000000010227db1a -[UISearchDisplayController _setTableViewVisible:inView:] + 916
	33  UIKit                               0x00000001021b2da3 -[UISearchBar(UISearchBarStatic) _searchFieldEditingChanged] + 162
	34  UIKit                               0x0000000101eb2d62 -[UIApplication sendAction:to:from:forEvent:] + 75
	35  UIKit                               0x0000000101fc450a -[UIControl _sendActionsForEvents:withEvent:] + 467
	36  UIKit                               0x00000001025e48a2 -[UITextField fieldEditorDidChange:] + 204
	37  UIKit                               0x00000001025ec9ec -[UITextInputController _sendDelegateChangeNotificationsForText:selection:] + 118
	38  UIKit                               0x00000001025ee6a9 -[UITextInputController _insertText:fromKeyboard:] + 643
	39  UIKit                               0x00000001025eede8 -[UITextInputController insertText:] + 281
	40  UIKit                               0x00000001020b5835 -[UIKeyboardImpl insertText:] + 89
	41  UIKit                               0x00000001020b22a2 -[UIKeyboardImpl performKeyboardOutput:] + 487
	42  UIKit                               0x00000001020b1f65 __55-[UIKeyboardImpl handleKeyboardInput:executionContext:]_block_invoke_2 + 136
	43  UIKit                               0x00000001026090e4 -[UIKeyboardTaskQueue continueExecutionOnMainThread] + 332
	44  Foundation                          0x000000010174169a __NSThreadPerformPerform + 299
	45  CoreFoundation                      0x00000001031ed431 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	46  CoreFoundation                      0x00000001031e32fd __CFRunLoopDoSources0 + 269
	47  CoreFoundation                      0x00000001031e2934 __CFRunLoopRun + 868
	48  CoreFoundation                      0x00000001031e2366 CFRunLoopRunSpecific + 470
	49  GraphicsServices                    0x000000010596ea3e GSEventRunModal + 161
	50  UIKit                               0x0000000101eb18c0 UIApplicationMain + 1282
	51  BJCPStyles                          0x000000010001e3df main + 111
	52  libdyld.dylib                       0x00000001045ed145 start + 1
	53  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NoMethodError
```

**Comment by jamonholmgren** [comment]
Resolved, @markrickert ?

**Comment by markrickert** [comment]
Yup :)
